Enable support for Ubuntu 24.04 (#51) (#52)
* Build Updates for Ubuntu24.04 (#50)

* update cmake version for u24

* temp: override client repo tag

* remove werror

* fix0 - redefinition error

Error -
```
/tmp/build/javacpp-presets/tritonserver/cppbuild/tritonbuild/developer_tools/server/include/triton/developer_tools/server_wrapper.h:413:58: error: redefinition of default argument for 'typename std::enable_if<(! std::is_same<typename std::iterator_traits< <template-parameter-1-1> >::value_type, std::__cxx11::basic_string<char> >::value)>::type* <anonymous>'
  413 |                            std::string>::value>::type* = nullptr>
      |                                                          ^~~~~~~
/tmp/build/javacpp-presets/tritonserver/cppbuild/tritonbuild/developer_tools/server/include/triton/developer_tools/server_wrapper.h:316:41: note: original definition appeared here
  316 |           std::string>::value>::type* = nullptr>
      |                                         ^~~~~~~
make[2]: *** [CMakeFiles/triton-developer_tools-server.dir/build.make:76: CMakeFiles/triton-developer_tools-server.dir/src/server_wrapper.cc.o] Error 1
```

* fix1 - redefinition error

* Revert "temp: override client repo tag"

This reverts commit 9f8ea3d33c661325e1a81b793399e7a94a7dbf8e.

* Update server/install_dependencies_and_build.sh

---------

Co-authored-by: Anant Sharma <anants@nvidia.com>